[project]
name = "resmed-support-agent"
version = "0.1.0"
description = "A production-ready, conversational AI agent that can diagnose common issues and provide compliance checks for a simulated fleet of cloud-connected ResMed CPAP devices."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.8",
    "langchain-openai>=0.3.6",
    "langgraph>=0.2.73",
    "pre-commit>=4.1.0",
    "python-dotenv>=1.0.1",
    "streamlit-chat>=0.1.1",
    "streamlit>=1.42.1",
    "uvicorn>=0.34.0",
    "watchdog>=6.0.0",
    "truefoundry>=0.10.0,<0.11.0",
    "traceloop-sdk==0.39.0",
    "jupyter>=1.1.1",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pylint>=3.3.8",
    "httpx>=0.28.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
